### PR TITLE
Create 2021-07-25-Installing-PyTorch.md

### PR DESCRIPTION
**Pull request by khushi-411**
Hi, 
This PR is the blog post for setting up PyTorch from the source. Please have a look.

cc: @kshitij12345 @krshrimali

### CODE REVIEW

**Comment by krshrimali** [comment]
Thanks, @khushi-411 - I need to set up the build server locally for the blog, will test it, and make changes necessary. I'll take it from here.

**Comment by kshitij12345** [comment]
@krshrimali gentle ping :)

**Comment by krshrimali** [comment]
Made the final edits, I think we are good to go. Thanks, @khushi-411 - really well done. @kshitij12345 - Thank you for reviewing the PR! 🎉 Merging this now.

**Comment by krshrimali** [comment]
Added the link to the blog in the video: https://www.youtube.com/watch?v=AIkvOtHJZeo&list=PLFYhn53SnsgJI2jjjsV0bZu3tdfi361wv&index=1. Also check the demo of the published blog here: https://malloc-42.github.io/intro/2021/07/25/Installing-PyTorch/. Thanks!

cc: @kshitij12345 @khushi-411

**Comment by khushi-411** [comment]
Thanks, @kshitij12345 and @krshrimali for reviewing the PR.❤

**Pull request merged**
